export const root: string;
export const noapi: string;
export const banner: string;
export const content: string;
export const left: string;
export const leftHeader: string;
export const leftSelect: string;
export const leftTitle: string;
export const right: string;
